<?php
$data = [
    0 =>
        [
            'id' => 1,
            'type' => 'file',
            'pid' => 0,
            'name' => 'dashboard',
            'route' => '',
            'title' => 'Dashboard',
            'icon' => 'fa fa-dashboard',
            'condition' => '',
            'remark' => 'Dashboard tips',
            'ismenu' => 1,
            'weigh' => 143,
            'status' => 'normal',
        ],
    [
        'id' => 2,
        'type' => 'file',
        'pid' => 0,
        'name' => 'general',
        'route' => '',
        'title' => 'General',
        'icon' => 'fa fa-cogs',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 137,
        'status' => 'normal',
    ],
    [
        'id' => 4,
        'type' => 'file',
        'pid' => 123,
        'name' => 'addon',
        'route' => '',
        'title' => '插件管理',
        'icon' => 'fa fa-rocket',
        'condition' => '',
        'remark' => 'Addon tips',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 5,
        'type' => 'file',
        'pid' => 0,
        'name' => 'auth',
        'route' => '',
        'title' => '权限管理',
        'icon' => 'fa fa-group',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 99,
        'status' => 'normal',
    ],
    [
        'id' => 6,
        'type' => 'file',
        'pid' => 2,
        'name' => 'general/config',
        'route' => 'general.config/index',
        'title' => 'Config',
        'icon' => 'fa fa-cog',
        'condition' => '',
        'remark' => 'Config tips',
        'ismenu' => 1,
        'weigh' => 60,
        'status' => 'normal',
    ],
    [
        'id' => 7,
        'type' => 'file',
        'pid' => 2,
        'name' => 'general/attachment',
        'route' => 'general.attachment/index',
        'title' => 'Attachment',
        'icon' => 'fa fa-file-image-o',
        'condition' => '',
        'remark' => 'Attachment tips',
        'ismenu' => 1,
        'weigh' => 53,
        'status' => 'normal',
    ],
    [
        'id' => 8,
        'type' => 'file',
        'pid' => 2,
        'name' => 'general/profile',
        'route' => 'general.profile/index',
        'title' => 'Profile',
        'icon' => 'fa fa-user',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 34,
        'status' => 'normal',
    ],
    [
        'id' => 9,
        'type' => 'file',
        'pid' => 5,
        'name' => 'auth/admin',
        'route' => 'auth.admin/index',
        'title' => 'Admin',
        'icon' => 'fa fa-user',
        'condition' => '',
        'remark' => 'Admin tips',
        'ismenu' => 1,
        'weigh' => 118,
        'status' => 'normal',
    ],
    [
        'id' => 10,
        'type' => 'file',
        'pid' => 5,
        'name' => 'auth/adminlog',
        'route' => 'auth.adminlog/index',
        'title' => '管理员日志',
        'icon' => 'fa fa-list-alt',
        'condition' => '',
        'remark' => 'Admin log tips',
        'ismenu' => 0,
        'weigh' => 113,
        'status' => 'hidden',
    ],
    [
        'id' => 11,
        'type' => 'file',
        'pid' => 5,
        'name' => 'auth/group',
        'route' => 'auth.group/index',
        'title' => 'Group',
        'icon' => 'fa fa-group',
        'condition' => '',
        'remark' => 'Group tips',
        'ismenu' => 1,
        'weigh' => 109,
        'status' => 'normal',
    ],
    [
        'id' => 12,
        'type' => 'file',
        'pid' => 5,
        'name' => 'auth/rule',
        'route' => 'auth.rule/index',
        'title' => 'Rule',
        'icon' => 'fa fa-bars',
        'condition' => '',
        'remark' => 'Rule tips',
        'ismenu' => 1,
        'weigh' => 104,
        'status' => 'normal',
    ],
    [
        'id' => 13,
        'type' => 'file',
        'pid' => 1,
        'name' => 'dashboard/index',
        'route' => '',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 136,
        'status' => 'normal',
    ],
    [
        'id' => 14,
        'type' => 'file',
        'pid' => 1,
        'name' => 'dashboard/add',
        'route' => '',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 135,
        'status' => 'normal',
    ],
    [
        'id' => 15,
        'type' => 'file',
        'pid' => 1,
        'name' => 'dashboard/del',
        'route' => '',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 133,
        'status' => 'normal',
    ],
    [
        'id' => 16,
        'type' => 'file',
        'pid' => 1,
        'name' => 'dashboard/edit',
        'route' => '',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 134,
        'status' => 'normal',
    ],
    [
        'id' => 17,
        'type' => 'file',
        'pid' => 1,
        'name' => 'dashboard/multi',
        'route' => '',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 132,
        'status' => 'normal',
    ],
    [
        'id' => 18,
        'type' => 'file',
        'pid' => 6,
        'name' => 'general/config/index',
        'route' => 'general.config/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 52,
        'status' => 'normal',
    ],
    [
        'id' => 19,
        'type' => 'file',
        'pid' => 6,
        'name' => 'general/config/add',
        'route' => 'general.config/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 51,
        'status' => 'normal',
    ],
    [
        'id' => 20,
        'type' => 'file',
        'pid' => 6,
        'name' => 'general/config/edit',
        'route' => 'general.config/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 50,
        'status' => 'normal',
    ],
    [
        'id' => 21,
        'type' => 'file',
        'pid' => 6,
        'name' => 'general/config/del',
        'route' => 'general.config/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 49,
        'status' => 'normal',
    ],
    [
        'id' => 22,
        'type' => 'file',
        'pid' => 6,
        'name' => 'general/config/multi',
        'route' => 'general.config/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 48,
        'status' => 'normal',
    ],
    [
        'id' => 23,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/index',
        'route' => 'general.attachment/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Attachment tips',
        'ismenu' => 0,
        'weigh' => 59,
        'status' => 'normal',
    ],
    [
        'id' => 24,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/select',
        'route' => 'general.attachment/select',
        'title' => 'Select attachment',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 58,
        'status' => 'normal',
    ],
    [
        'id' => 25,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/add',
        'route' => 'general.attachment/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 57,
        'status' => 'normal',
    ],
    [
        'id' => 26,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/edit',
        'route' => 'general.attachment/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 56,
        'status' => 'normal',
    ],
    [
        'id' => 27,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/del',
        'route' => 'general.attachment/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 55,
        'status' => 'normal',
    ],
    [
        'id' => 28,
        'type' => 'file',
        'pid' => 7,
        'name' => 'general/attachment/multi',
        'route' => 'general.attachment/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 54,
        'status' => 'normal',
    ],
    [
        'id' => 29,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/index',
        'route' => 'general.profile/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 33,
        'status' => 'normal',
    ],
    [
        'id' => 30,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/update',
        'route' => 'general.profile/update',
        'title' => 'Update profile',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 32,
        'status' => 'normal',
    ],
    [
        'id' => 31,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/add',
        'route' => 'general.profile/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 31,
        'status' => 'normal',
    ],
    [
        'id' => 32,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/edit',
        'route' => 'general.profile/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 30,
        'status' => 'normal',
    ],
    [
        'id' => 33,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/del',
        'route' => 'general.profile/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 29,
        'status' => 'normal',
    ],
    [
        'id' => 34,
        'type' => 'file',
        'pid' => 8,
        'name' => 'general/profile/multi',
        'route' => 'general.profile/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 28,
        'status' => 'normal',
    ],
    [
        'id' => 40,
        'type' => 'file',
        'pid' => 9,
        'name' => 'auth/admin/index',
        'route' => 'auth.admin/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Admin tips',
        'ismenu' => 0,
        'weigh' => 117,
        'status' => 'normal',
    ],
    [
        'id' => 41,
        'type' => 'file',
        'pid' => 9,
        'name' => 'auth/admin/add',
        'route' => 'auth.admin/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 116,
        'status' => 'normal',
    ],
    [
        'id' => 42,
        'type' => 'file',
        'pid' => 9,
        'name' => 'auth/admin/edit',
        'route' => 'auth.admin/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 115,
        'status' => 'normal',
    ],
    [
        'id' => 43,
        'type' => 'file',
        'pid' => 9,
        'name' => 'auth/admin/del',
        'route' => 'auth.admin/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 114,
        'status' => 'normal',
    ],
    [
        'id' => 44,
        'type' => 'file',
        'pid' => 10,
        'name' => 'auth/adminlog/index',
        'route' => 'auth.adminlog/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Admin log tips',
        'ismenu' => 0,
        'weigh' => 112,
        'status' => 'normal',
    ],
    [
        'id' => 45,
        'type' => 'file',
        'pid' => 10,
        'name' => 'auth/adminlog/detail',
        'route' => 'auth.adminlog/detail',
        'title' => 'Detail',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 111,
        'status' => 'normal',
    ],
    [
        'id' => 46,
        'type' => 'file',
        'pid' => 10,
        'name' => 'auth/adminlog/del',
        'route' => 'auth.adminlog/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 110,
        'status' => 'normal',
    ],
    [
        'id' => 47,
        'type' => 'file',
        'pid' => 11,
        'name' => 'auth/group/index',
        'route' => 'auth.group/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Group tips',
        'ismenu' => 0,
        'weigh' => 108,
        'status' => 'normal',
    ],
    [
        'id' => 48,
        'type' => 'file',
        'pid' => 11,
        'name' => 'auth/group/add',
        'route' => 'auth.group/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 107,
        'status' => 'normal',
    ],
    [
        'id' => 49,
        'type' => 'file',
        'pid' => 11,
        'name' => 'auth/group/edit',
        'route' => 'auth.group/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 106,
        'status' => 'normal',
    ],
    [
        'id' => 50,
        'type' => 'file',
        'pid' => 11,
        'name' => 'auth/group/del',
        'route' => 'auth.group/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 105,
        'status' => 'normal',
    ],
    [
        'id' => 51,
        'type' => 'file',
        'pid' => 12,
        'name' => 'auth/rule/index',
        'route' => 'auth.rule/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Rule tips',
        'ismenu' => 0,
        'weigh' => 103,
        'status' => 'normal',
    ],
    [
        'id' => 52,
        'type' => 'file',
        'pid' => 12,
        'name' => 'auth/rule/add',
        'route' => 'auth.rule/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 102,
        'status' => 'normal',
    ],
    [
        'id' => 53,
        'type' => 'file',
        'pid' => 12,
        'name' => 'auth/rule/edit',
        'route' => 'auth.rule/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 101,
        'status' => 'normal',
    ],
    [
        'id' => 54,
        'type' => 'file',
        'pid' => 12,
        'name' => 'auth/rule/del',
        'route' => 'auth.rule/del',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 100,
        'status' => 'normal',
    ],
    [
        'id' => 55,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/index',
        'route' => '',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => 'Addon tips',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 56,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/add',
        'route' => '',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 57,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/edit',
        'route' => '',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 58,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/del',
        'route' => '',
        'title' => 'Delete',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 59,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/downloaded',
        'route' => '',
        'title' => 'Local addon',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 60,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/state',
        'route' => '',
        'title' => 'Update state',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 63,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/config',
        'route' => '',
        'title' => 'Setting',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 64,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/refresh',
        'route' => '',
        'title' => 'Refresh',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],
    [
        'id' => 65,
        'type' => 'file',
        'pid' => 4,
        'name' => 'addon/multi',
        'route' => '',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 66,
        'type' => 'file',
        'pid' => 0,
        'name' => 'user',
        'route' => '',
        'title' => '会员管理',
        'icon' => 'fa fa-list',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'hidden',
    ],

    [
        'id' => 67,
        'type' => 'file',
        'pid' => 66,
        'name' => 'user/user',
        'route' => 'user.user/index',
        'title' => 'User',
        'icon' => 'fa fa-user',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 68,
        'type' => 'file',
        'pid' => 67,
        'name' => 'user/user/index',
        'route' => 'user.user/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 69,
        'type' => 'file',
        'pid' => 67,
        'name' => 'user/user/edit',
        'route' => 'user.user/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 70,
        'type' => 'file',
        'pid' => 67,
        'name' => 'user/user/add',
        'route' => 'user.user/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 71,
        'type' => 'file',
        'pid' => 67,
        'name' => 'user/user/del',
        'route' => 'user.user/del',
        'title' => 'Del',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 72,
        'type' => 'file',
        'pid' => 67,
        'name' => 'user/user/multi',
        'route' => 'user.user/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 73,
        'type' => 'file',
        'pid' => 66,
        'name' => 'user/group',
        'route' => 'user.group/index',
        'title' => 'User group',
        'icon' => 'fa fa-users',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 74,
        'type' => 'file',
        'pid' => 73,
        'name' => 'user/group/add',
        'route' => 'user.group/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 75,
        'type' => 'file',
        'pid' => 73,
        'name' => 'user/group/edit',
        'route' => 'user.group/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 76,
        'type' => 'file',
        'pid' => 73,
        'name' => 'user/group/index',
        'route' => 'user.group/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 77,
        'type' => 'file',
        'pid' => 73,
        'name' => 'user/group/del',
        'route' => 'user.group/del',
        'title' => 'Del',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 78,
        'type' => 'file',
        'pid' => 73,
        'name' => 'user/group/multi',
        'route' => 'user.group/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 79,
        'type' => 'file',
        'pid' => 66,
        'name' => 'user/rule',
        'route' => 'user.rule/index',
        'title' => '会员规则',
        'icon' => 'fa fa-gg',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 80,
        'type' => 'file',
        'pid' => 79,
        'name' => 'user/rule/index',
        'route' => 'user.rule/index',
        'title' => 'View',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 81,
        'type' => 'file',
        'pid' => 79,
        'name' => 'user/rule/del',
        'route' => 'user.rule/del',
        'title' => 'Del',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 82,
        'type' => 'file',
        'pid' => 79,
        'name' => 'user/rule/add',
        'route' => 'user.rule/add',
        'title' => 'Add',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 83,
        'type' => 'file',
        'pid' => 79,
        'name' => 'user/rule/edit',
        'route' => 'user.rule/edit',
        'title' => 'Edit',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 84,
        'type' => 'file',
        'pid' => 79,
        'name' => 'user/rule/multi',
        'route' => 'user.rule/multi',
        'title' => 'Multi',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 85,
        'type' => 'file',
        'pid' => 123,
        'name' => 'command',
        'route' => '',
        'title' => '在线命令管理',
        'icon' => 'fa fa-terminal',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 86,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/index',
        'route' => 'command.index/index',
        'title' => '查看',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 87,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/add',
        'route' => 'command.add/index',
        'title' => '添加',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 88,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/detail',
        'route' => 'command.detail/index',
        'title' => '详情',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 89,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/execute',
        'route' => 'command.execute/index',
        'title' => '运行',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 90,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/del',
        'route' => 'command.del/index',
        'title' => '删除',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 91,
        'type' => 'file',
        'pid' => 85,
        'name' => 'command/multi',
        'route' => 'command.multi/index',
        'title' => '批量更新',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 92,
        'type' => 'file',
        'pid' => 123,
        'name' => 'general/databasebak',
        'route' => 'general.databasebak/index',
        'title' => '数据库管理',
        'icon' => 'fa fa-database',
        'condition' => '',
        'remark' => '可在线进行一些简单的数据库表优化或修复,查看表结构和数据。也可以进行SQL语句的操作',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 93,
        'type' => 'file',
        'pid' => 92,
        'name' => 'general/databasebak/index',
        'route' => 'general.databasebak/index',
        'title' => '查看',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 94,
        'type' => 'file',
        'pid' => 92,
        'name' => 'general/databasebak/query',
        'route' => 'general.databasebak/query',
        'title' => '查询',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 95,
        'type' => 'file',
        'pid' => 92,
        'name' => 'general/databasebak/backup',
        'route' => 'general.databasebak/backup',
        'title' => '备份',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 96,
        'type' => 'file',
        'pid' => 92,
        'name' => 'general/databasebak/restore',
        'route' => 'general.databasebak/restore',
        'title' => '恢复',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 97,
        'type' => 'file',
        'pid' => 123,
        'name' => 'general/crontab',
        'route' => 'general.crontab/index',
        'title' => '定时任务',
        'icon' => 'fa fa-tasks',
        'condition' => '',
        'remark' => '类似于Linux的Crontab定时任务,可以按照设定的时间进行任务的执行,目前支持四种任务:请求URL、执行SQL、执行Shell、执行Function',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 98,
        'type' => 'file',
        'pid' => 97,
        'name' => 'general/crontab/index',
        'route' => 'general.crontab/index',
        'title' => '查看',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 99,
        'type' => 'file',
        'pid' => 97,
        'name' => 'general/crontab/add',
        'route' => 'general.crontab/add',
        'title' => '添加',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 100,
        'type' => 'file',
        'pid' => 97,
        'name' => 'general/crontab/edit',
        'route' => 'general.crontab/edit',
        'title' => '编辑 ',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 101,
        'type' => 'file',
        'pid' => 97,
        'name' => 'general/crontab/del',
        'route' => 'general.crontab/del',
        'title' => '删除',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 102,
        'type' => 'file',
        'pid' => 97,
        'name' => 'general/crontab/multi',
        'route' => 'general.crontab/multi',
        'title' => '批量更新',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 113,
        'type' => 'file',
        'pid' => 0,
        'name' => 'wechat',
        'route' => '',
        'title' => '小程序管理',
        'icon' => 'fa fa-wechat',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 114,
        'type' => 'file',
        'pid' => 113,
        'name' => 'wechat/user',
        'route' => 'wechat.user/index',
        'title' => '小程序用户',
        'icon' => 'fa fa-address-book',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 115,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/index',
        'route' => 'wechat.user/index',
        'title' => '查看',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 116,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/recyclebin',
        'route' => 'wechat.user/recyclebin',
        'title' => '回收站',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 117,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/add',
        'route' => 'wechat.user/add',
        'title' => '添加',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 118,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/edit',
        'route' => 'wechat.user/edit',
        'title' => '编辑',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 119,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/del',
        'route' => 'wechat.user/del',
        'title' => '删除',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 120,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/destroy',
        'route' => 'wechat.user/destroy',
        'title' => '真实删除',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 121,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/restore',
        'route' => 'wechat.user/restore',
        'title' => '还原',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 122,
        'type' => 'file',
        'pid' => 114,
        'name' => 'wechat/user/multi',
        'route' => 'wechat.user/multi',
        'title' => '批量更新',
        'icon' => 'fa fa-circle-o',
        'condition' => '',
        'remark' => '',
        'ismenu' => 0,
        'weigh' => 0,
        'status' => 'normal',
    ],

    [
        'id' => 123,
        'type' => 'file',
        'pid' => 0,
        'name' => 'developer',
        'route' => '',
        'title' => '开发工具',
        'icon' => 'fa fa-codepen',
        'condition' => '',
        'remark' => '',
        'ismenu' => 1,
        'weigh' => 0,
        'status' => 'normal',
    ],
];

foreach ($data as $v) {
    $model = new \app\admin\model\AuthRule;
    $model->save($v);
}
